### ISSUE TITLE
Frequent duplicate results

### ISSUE THREAD

**Issue by raphaelshklarek** [brianpetro/obsidian-smart-connections#1077]
Hi, thank you so much for your awesome plugin. Your work is invaluable to me!

I've encountered an issue for quite a while now, where results in the smart connections view are duplicate, with exactly the same text with the sole difference that one includes the heading above the block and one doesn't.

Here is a screenshot to illustrate. I've checked and this happens in almost every note. I've tried reload sources, clean up and clear data but nothing changed it. I'm running the nomic 1.5 model and my vault includes 718 notes as of now, of which some are maps of content, some are longer conceptual notes and some are more atomic.

Thanks for your support 🙏 

<img width="1281" alt="Image" src="https://github.com/user-attachments/assets/b8899bc7-625d-4a56-b2c6-8fdd6c06e4ae" />

**Comment by brianpetro** [comment]
@rshklarek thanks again for bringing this to my attention 😊

The issue should now be fixed in `v3.0.52`.

In short, the `should_embed` logic was failing because blocks were being queued for embedding before all blocks from the same note were created. The `should_embed` logic partially works by checking for overlap in adjacent blocks.

The screenshots below show how the issue could be visualized using the "note inspect modal".

Broken:
![Image](https://github.com/user-attachments/assets/4edf4898-6f63-4ac2-805f-8ca69d397271)

Working:

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/4118d810-4036-4018-9a5d-be53b1104393" />

Thanks for your help in getting this issue resolved 😊🌴

**Comment by raphaelshklarek** [comment]
Oh very interesting, cool! Thank you so much for looking into it 🙏  Should I do anything such as reload or clear data to enact the changes? Right now after updating the plugin the issue persists.

**Comment by brianpetro** [comment]
@rshklarek you can try the "Clean-up data" button (fastest). If that doesn't resolve it, "Clear sources data" and then "Reload sources" 🌴

**Comment by raphaelshklarek** [comment]
Unfortunately that didn't solve it. The error persists and when I open the inspector the duplicate blocks say "should embed | vectorized". Again, the only difference between the embedded blocks is that one includes the heading above it and the other starts right below it.

<img width="1104" alt="Image" src="https://github.com/user-attachments/assets/44079bc7-d313-415f-9ca5-44905973f5cb" />

<img width="1104" alt="Image" src="https://github.com/user-attachments/assets/e3167b3c-b406-4d19-9b9d-1a300c14e006" />

**Comment by brianpetro** [comment]
Thanks for the screenshots. I'll have to dig a bit deeper 🌴

**Comment by Medenor** [comment]
Hello

Same issue here :

![Image](https://github.com/user-attachments/assets/951cd351-40b8-4141-8853-eb32c56f3ccd)

In duplicated entries, the first one is always empty but correctly linked to the other note, while the second contains the other note content and is correctly linked to it.

I'm using Obsidian v1.9.12 and Smart Connections 3.0.78
