### ISSUE TITLE
Embed requests to Ollama (local) API include full/non-chuncked documents exceeding supported context size

### ISSUE THREAD

**Issue by henfiber** [brianpetro/obsidian-smart-connections#1098]
Hello, thank you for this plugin suite.

I am trying to make it work with ollama/local embeddings models.

I was getting errors and when inspecting (with Ctrl-Shift-I) the /api/embed requests, and also through logs, I noticed that the documents sent to the model often exceed the context size of the model (usually 512 or 8192 tokens), leading to almost all requests rejected (because of the default 30-documents batching, almost always one of them is greater than 8192 tokens).

Does the plugin perform chunking before embedding the documents? I expected that some of your smart-entities/smart-blocks would be utilized to chunk the documents but apparently either my notes are not structured enough or they are not used? In any case, even if those are not detected, I would expect the input to be chunked on the max context length supported by the model.

I inspected your code at [smart-embed-model/ollama.js](https://github.com/brianpetro/jsbrains/blob/main/smart-embed-model/adapters/ollama.js ) and it seems to trim the text on max tokens but this seems not to be working? Just looking at the code flow, maybe it is because you use `max_input_tokens` at `parse_model_data()` and `max_tokens` in other places? (maybe not, just skimmed over the code). 

<details><summary>Example model details returned from /api/show</summary>
<p>

```js
fetch("http://localhost:11434/api/show", {
  "body": "{\"model\":\"nomic-embed-text-v1.5\"}",
  "method": "POST",
});
```

```json
{
    "details": {
        "format": "gguf",
        "family": "bert",
        "families": [
            "bert"
        ],
        "parameter_size": "137M",
        "quantization_level": "Q8_0"
    },
    "model_info": {
        "general.architecture": "nomic-bert",
        "llama.context_length": 8192
    },
    "capabilities": [
        "embedding"
    ],
    "modified_at": "0001-01-01T00:00:00Z"
}
```

</p>
</details> 

With the built-in transoformers models I do not have this issue (but it is a bit slow for me with only legacy version working without a dedicated GPU, and wanted to use ollama/llama.cpp for multi-threaded iGPU support and not blocking the Obsidian main thread).

Thanks in advance.

**Comment by brianpetro** [comment]
@henfiber thanks for debugging this and the helpful report 😊

Unfortunately, the issue is a bit more complicated than the naming issue (though that was erroneous and needed to be fixed, so thanks for pointing that out).

I'm working on a fix now, update coming shortly 🌴

**Comment by brianpetro** [comment]
@henfiber should be fixed in `v3.0.37`, let me know how it goes 🌴

**Comment by henfiber** [comment]
Thank you for your quick response. These changes seem to help but the issue still persists and I have figured out that the last cause seems to be the token estimation formula. 

I progressively lowered the characters ÷ token ratio in the formula:

```js
tokens = chars /  3.7
```

and found out that the higher number that does not cause any errors in my own vault is **1.25**.

i.e. tokens = chars / 1.25

(with a ratio of 1.3 - 1.4 about 10% of the requests failed. With 3.7, about 90-95% fail).

This is caused by some notes that have a lot of symbols (code, markdown tables with a lot of "------" etc.) which are usually represented by a single token lowering the overall ratio.

Since requests are batched in groups of 30, just one of those 30 needs to have a low token to character ratio for the whole request/batch to fail.

Using a fast tokenizer such as [niieani/gpt-tokenizer](https://github.com/niieani/gpt-tokenizer) may be the most appropriate. Not all models use the same tokenizer but the differences should be relatively small and much closer than a fixed tokens/characters ratio. With a safe buffer it should probably work for most cases.

**Comment by brianpetro** [comment]
I'm pretty sure Ollama is supposed to automatically truncate inputs that are too large. Is it possible that feature is turned off in your ollama instance? 🌴

**Comment by brianpetro** [comment]
@henfiber this might be a quick fix for you. You can configure the `max_tokens` in the `.smart-env/smart_env.json` file like this: 

![Image](https://github.com/user-attachments/assets/7b70bb86-c160-4bb3-852b-c56580337dad)

🌴

**Comment by henfiber** [comment]
Thanks for your quick response. 

I'm using an [Ollama emulation service](https://github.com/kooshi/llama-swappo) because Ollama does not support Vulkan acceleration and some other customization options available in plain llama.cpp.  Maybe ollama automatically truncates input while llama.cpp prefers to error out so the issue is fixed on the client (i.e. better to chunk/split instead of truncation). I personally added the ollama embeddings (/api/embed) endpoints to this service a few days ago.

I will experiment with your suggestion and let you know. I suppose that this requires editing the currently selected embedding model and then restart Obsidian so it is loaded. Or I will just use a sed script to change the 3.7 multiplier to 1.25. I will compare the two options and let you know.

**Comment by brianpetro** [comment]
Good to know, I wasn't aware of the emulation service. And it seems like that must be the case. In the regular Ollama, there is a parameter that can be added to the request that causes Ollama to throw an error when the embedding input is oversized, but I very intentionally did not apply that parameter.

Editing the `.smart-env/smart_env.json` file in the root of your vault should only require restarting Obsidian for the change to take effect. There shouldn't be anything that overwrites the setting (though I haven't thoroughly tested this). But whatever is easiest for you makes the most sense to me 🌴

**Comment by henfiber** [comment]
I added `max_tokens`  equal to ctx_size * 1.25 / 3.7 = 8192 * 1.25/3.7 = **2767**  
under ollama at `.smart-env/smart_env.json` :

```json
      "ollama": {
        "model_key": "nomic-embed-text-v1",
        "host": "http://localhost:11434",
        "max_tokens": 2767
      },
```

and restarted obsidian, but it did not work. I got a few chunks greater than 8192:

```
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot launch_slot_: id  0 | task 139 | processing task
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot update_slots: id  0 | task 139 | new prompt, n_ctx_slot = 8192, n_keep = 0, n_prompt_tokens = 10208
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot      release: id  0 | task 139 | stop processing: n_past = 0, truncated = 0
Ιουν 17 21:39:48 hptop llama-swap[127198]: srv    send_error: task id = 139, error: input is too large to process. increase the physical batch size
Ιουν 17 21:39:48 hptop llama-swap[127198]: srv  update_slots: no tokens to decode
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot launch_slot_: id  0 | task 140 | processing task
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot update_slots: id  0 | task 140 | new prompt, n_ctx_slot = 8192, n_keep = 0, n_prompt_tokens = 10265
Ιουν 17 21:39:48 hptop llama-swap[127198]: slot      release: id  0 | task 140 | stop processing: n_past = 0, truncated = 0
Ιουν 17 21:39:48 hptop llama-swap[127198]: srv    send_error: task id = 140, error: input is too large to process. increase the physical batch size
```

But since I've found a working solution by changing 3.7 to 1.25 (and I can apply quickly in new versions with a sed expression) no need to waste your time more with this. We can revisit in the future if more people face the same issue.

```sh
cp ./smart-connections/{main.js,main.js.bak} && sed -i 's/ 3.7)/ 1.25)/g' ./smart-connections/main.js
```

Thanks for your support.

**Comment by brianpetro** [comment]
Good to know. I wonder how those few chunks are slipping by 🤔. But we'll save that for another day. Thanks for the follow-up 🌴
