### ISSUE TITLE
Obsidian stuck after creating new notes

### ISSUE THREAD

**Issue by taofuns** [brianpetro/obsidian-smart-connections#626]
Obsidian stuck after creating new notes, and I noticed the console says “error importing blocks”, but I didn’t embed bocks in the setting. 

and I use the smart connect app, and the console shows that I’ve connected to the app, but it still stuck. 
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/80188597/7d8026a8-5894-4dea-9cfd-38242c560a4f)

**Comment by brianpetro** [comment]
Hi @taofuns 

And thank you for bringing this to my attention 😊

This bug should be fixed in `2.1.69`. 

Please update and let me know if it keeps happening. 

🌴

**Comment by taofuns** [comment]
> Hi @taofuns
> 
> And thank you for bringing this to my attention 😊
> 
> This bug should be fixed in `2.1.69`.
> 
> Please update and let me know if it keeps happening.
> 
> 🌴

thanks! but I’ve upgraded to `2.1.69`, but the problem still existed.
![image](https://github.com/brianpetro/obsidian-smart-connections/assets/80188597/bdc7e2ed-09a4-47c4-bef9-5de2efcfdc57)
