### ISSUE TITLE
Does not create any connections

### ISSUE THREAD

**Issue by Eleksar387** [brianpetro/obsidian-smart-connections#9]
I installed it manually because it won't show up in the community plugins section. Added the API key. But even after hours I just see "Making smart connections..." in the smart connections pane. I must be doing something wrong. Any ideas?

**Comment by brianpetro** [comment]
Thanks for making me aware of this @Eleksar387 😊

As it happens... the updates I made yesterday also included a bug. I just pushed an update that fixes the problem!

You should now see a "Create embeddings.json" button appear where you were seeing the persistent "Making smart connections..." message.

Also, if you aren't using it already, check out the "Obsidian42 - BRAT" plugin. It enables you to install by simply copy&pasting the link to this Github repo, and it also has the option to update the plugin automatically.

Thanks for checking out the plugin, and extra special thanks for making me aware of this issue!

**Comment by sussweb** [comment]
@brianpetro Thank you so much for looking into it! Unfortunately there is still no change for me. I've removed the extension. Installed BRAT (thx for this one!) and added smart-connections to brat. The plugin is visible and activated. But again I can just see "Makeing smart connections...". Is there a log I could check what the problem might be?

**Comment by brianpetro** [comment]
Hi @sussweb 

I just saw this. I hope this started working for you in the meantime. But if it didn't:

yes, you can check the "console log," you can learn how to access it here https://forum.obsidian.md/t/how-to-access-the-console/16703

This issue shows an example of what it looks like https://github.com/brianpetro/obsidian-smart-connections/issues/12

Please also let me know which patch version you're using. That could also help me figure this out. The patch version is the last number in the green circle in this screenshot:
![community-plugins-smart-connections-version](https://user-images.githubusercontent.com/1886014/211586894-37abf816-99a1-4e58-a6b8-419433ccc28b.png)

Thanks for following up about this!

**Comment by brianpetro** [comment]
Closing this to merge with https://github.com/brianpetro/obsidian-smart-connections/issues/13
